; This file was auto-generated by drush_make
core = 6.x

; Please fill the following out.
projects[pressflow][download][type] = ""; One of get, cvs, git, bzr, svn or hg
projects[pressflow][download][url] = ""; The url of the download
projects[pressflow][type] = "core"

; Modules
projects[admin][install_path] = "modules/sgd/admin"

projects[context][install_path] = "modules/sgd/context"

projects[ctools][install_path] = "modules/sgd/ctools"

projects[] = "data"
projects[devel][install_path] = "modules/devel/devel"

projects[features][install_path] = "modules/featues"

projects[] = "feeds"
projects[jquery_ui][install_path] = "modules/acquia/jquery_ui"

projects[] = "schema"
projects[views][install_path] = "modules/acquia/views"

; Themes
projects[acquia_slate][install_path] = "themes/acquia/acquia_slate"

projects[acquia_marina][install_path] = "themes/acquia/acquia_marina"

projects[zen_ninesixty][install_path] = "themes/sgd/zen_ninesixty"

projects[rootcandy][install_path] = "themes/sgd/rootcandy"

projects[zen][install_path] = "themes/sgd/zen/zen"

projects[] = "simply_modern"
